title: Skinnysmylee
description: skinnysmylee workshop 
repository: skinnysmylee/skinnysmylee.github.io
author:        smirnov ilia
url:           "https://skinnysmylee.github.io/"

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
